# Generated by Django 4.1.6 on 2023-02-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesapi',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercisesapi',
            name='directions',
            field=models.TextField(),
        ),
    ]
