# Generated by Django 4.1.6 on 2023-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exercise', '0002_alter_exercisesapi_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesapi',
            name='targetMuscle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisesapi',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
